---

- name: Craete the elastic cache subnet group
  register: elastic_cache_subnet_group
  elasticache_subnet_group:
    name: "{{ envname }}-elasticcache-subnet-group"
    description: "Subnet group for the elastic cache clust for environment {{ envname }}"
    region: "{{ region }}"
    state: present
    subnets: "{{ vpc_subnet.results|selectattr('subnet.tags.category', 'equalto', 'data')|list|map(attribute='subnet.id')|list }}"

- debug: var=elastic_cache_subnet_group


- name: Create the elastic cache cluster
  register: elastic_cache_instance
  elasticache:
    name: "{{ envname }}-{{ elasticcache.cache_engine }}"
    state: present
    region: "{{ region }}"
    engine: "{{ elasticcache.cache_engine }}"
    cache_engine_version: "{{ elasticcache.cache_engine_version }}"
    node_type: "{{ elasticcache.instance_type }}"
    num_nodes: 1
    cache_port: 6379
    wait: yes
    security_group_ids: "{{ vpc_sec_group.0.group_id }}"
    cache_subnet_group: "{{ envname }}-elasticcache-subnet-group"

- debug: var=elastic_cache_instance