---
- name: Create NAT instance
  with_items: "{{ subnets | selectattr('category', 'equalto', 'management') | list }}"
  ec2:
    termination_protection: yes
    region: '{{ region }}'
    keypair: 'ansible-{{ envname }}'
    image: "{{ nat_instance.image }}"
    instance_type: "{{ nat_instance.type }}"
    instance_tags:
      Name: "nat"
      environment: '{{ envname }}'
      roles: 'nat'
    count_tag:
      Name: "nat"
      environment: '{{ envname }}'
    exact_count: 1
    vpc_subnet_id: "{{ (vpc_subnet.results|selectattr('subnet.tags.net', 'equalto', item.name)|first).subnet.id }}"
    assign_public_ip: True
    wait: yes
    wait_timeout: 600
    source_dest_check: False
    group: "{{ nat_instance.groups }}"
  register: nat_instances

- debug: 
    var: nat_instances
    verbosity: 1