---

- name: Create S3 bucket for deployment
  register: s3_bucket_result
  s3_bucket:
    name: "{{ aws_s3_bucket_name }}"
    state: present
    region: "{{ region }}"
    tags:
      Name: "{{ aws_s3_bucket_name }}"
      environment: '{{ envname }}'

- debug:
    var: s3_bucket_result
    verbosity: 1

