---

- name: Create S3 bucket for deployment
  register: s3_bucket_result
  s3_bucket:
    name: "{{ envname }}-imagestore-bucket"
    state: present
    region: "{{ region }}"
    tags:
      Name: '{{ envname }}-imagestore-bucket'
      environment: '{{ envname }}'

- debug:
    var: s3_bucket_result
    verbosity: 1

- set_fact:
    aws_s3_bucket_name: "{{ envname }}-imagestore-bucket"