---
- name: Create security groups
  with_items: '{{ security_groups }}'
  ec2_group:
    description: '{{ item.description }}'
    name: '{{ item.name }}'
    vpc_id: '{{ ec2_vpc.vpc_id }}'
    region: '{{ region }}'
    state: present
    rules: '{{ item.rules|default(omit) }}'
  register: ec2_security_groups

- debug:
    var: ec2_security_groups.results
    verbosity: 1

- name: Tag the security groups for the environment
  with_items: "{{ ec2_security_groups.results }}"
  ec2_tag:
    region: "{{ region }}"
    resource: "{{ item.group_id }}"
    state: present
    tags:
      environment: "{{ envname }}"
      Name: "{{ item.item.name }}"