---
- name: Create instances
  with_items: '{{ instances }}'
  ec2:
    region: '{{ region }}'
    zone: '{{ item.az|default(availability_zone) }}'
    keypair: 'ansible-{{ envname }}'
    instance_type: '{{ item.type }}'
    image: '{{ item.image|default(ami) }}'
    groups: '{{ item.groups|default(["allow_vpc"]) }}'
    instance_tags:
      Name: '{{ item.name }}'
      environment: '{{ envname }}'
      roles: '{{ item.roles }}'
    count_tag:
      Name: '{{ item.name}}'
      environment: '{{ envname }}'
    exact_count: '{{ item.count|default("1") }}'
    vpc_subnet_id: "{{ (vpc_subnet.results|selectattr('subnet.tags.net', 'equalto', item.subnet)|first).subnet.id }}"
    assign_public_ip: '{{ item.subnet == "public" }}'
    wait: yes
    wait_timeout: 600
    #instance_profile_name: '{{ envname }}_{{ item.role }}'
    instance_profile_name: "{{ item.iam_role|default(envname+'_'+item.name) }}"
    source_dest_check: '{{ item.source_dest_check|default(omit) }}'
    volumes: '{{ item.volumes|default(omit) }}'
    ebs_optimized: '{{ item.ebs_optimized|default(False) }}'
    user_data: '{{ item.user_data|default(omit) }}'
  register: ec2_instances

