---
# tasks file for vpc
- include: assertions.yml
- include: iam.yml
- include: vpc.yml
- include: subnets.yml
- include: security_groups.yml
- include: keypair.yml
- include: rds.yml
  when: use_rds
  static: no
- include: nat_instances.yml
- include: routing_tables.yml
# db and redis
- include: infra_instances.yml
  when: create_infra_instances
  static: no
- include: ec2_instances.yml
- include: lb.yml
- include: s3.yml
