# This task comes early because the roles sometimes don't appear until some
# time has passed since the task finished.

- name: Remove machine specific IAM roles
  with_items: '{{ instances }}'
  iam:
    iam_type: role
    name: '{{ envname }}_{{ item.name }}'
    state: absent


- name: Remove RDSFullAccess policy
  iam_policy:
    iam_type: role
    state: absent
    policy_name: "{{ envname }}-rds-full-access"
    iam_name: "{{ envname }}-ansible-controller-role"
   
- name: Remove EC2FullAccess policy
  iam_policy:
    iam_type: role
    state: absent
    policy_name: "{{ envname }}-ec2-full-access"
    iam_name: "{{ envname }}-ansible-controller-role"

- name: Remove IAMFullAccess policy
  iam_policy:
    iam_type: role
    state: absent
    policy_name: "{{ envname }}-iam-full-access"
    iam_name: "{{ envname }}-ansible-controller-role"

- name: Remove ElasticCacheFullAccess policy
  iam_policy:
    iam_type: role
    state: absent
    policy_name: "{{ envname }}-escache-full-access"
    iam_name: "{{ envname }}-ansible-controller-role"

- name: Remove S3FullAccess policy
  iam_policy:
    iam_type: role
    state: absent
    policy_name: "{{ envname }}-s3-full-access"
    iam_name: "{{ envname }}-ansible-controller-role"

- name: Remove ansible-controller IAM role
  iam:
    iam_type: role
    name: "{{ envname }}-ansible-controller-role"
    state: absent