---
- include: ec2_instances.yml
- include: lb.yml
- include: rds.yml
  when: use_data_cloud_services
- include: elastic_cache.yml
  when: use_data_cloud_services
- include: routing_tables.yml
- include: security_groups.yml
- include: subnets.yml
- include: vpc.yml
- include: iam.yml
- include: s3.yml
- include: keypair.yml