---

- name: delete all security groups
  ec2_group:
    region: "{{ region }}"
    name: "{{ item[0] }}"
    description: "deleted security group"
    vpc_id: "{{ item[0] }}"
    state: absent
  with_nested:
    - "{{ vpcids }}"
    - "{{ security_groups | map(attribute='name') | list }}"
  tags: ['delete']
    
