---
- name: remove VPC internet gateway
  ec2_vpc_igw:
    vpc_id: "{{ item }}"
    region: "{{ region }}"
    state: absent
  with_items: "{{ vpcids }}"
  tags: ['delete']
    
- name: delete all VPCs
  ec2_vpc:
    state: absent
    vpc_id: "{{ item }}"
    region: "{{ region }}"
    resource_tags: {"environment": "{{ envname }}"}
  with_items:
    - "{{ vpcids }}"
  tags: ['delete']
